[build]
cc = "clang"
src = "source"
incl = [ "include" ]
out = "target"
obj = "target/build"

[build.cpp]
std = "c++20"

[data_plugin]
plug = "data_plugin"

[paint]
exe = "nwgepaint"
link = [ "/subsystem:windows" ]
libs = [ "SDL2_image" ]

[snake]
exe = "nwgesnake"
link = [ "/subsystem:windows" ]

[pong]
exe = "nwgepong"
link = [ "/subsystem:windows" ]

[breakout]
exe = "nwgebreakout"
link = [ "/subsystem:windows" ]
